import { useState } from 'react';
import { Check, Copy, ExternalLink, ShieldAlert, Sparkles } from 'lucide-react';
import type { AnalysisResult, RiskLevel } from '../types';

export const riskLabel=(risk:RiskLevel)=>({safe:'SAFE',low:'LOW RISK',medium:'MEDIUM RISK',high:'HIGH RISK',critical:'CRITICAL'}[risk]);
export function RiskBadge({risk}:{risk:RiskLevel}){return <span className={`risk-badge risk-${risk}`}><span className="risk-dot"/>{riskLabel(risk)}</span>}
export function RiskScore({result}:{result:AnalysisResult}){return <div className={`score-ring risk-${result.riskLevel}`}><strong>{result.riskScore}</strong><span>/ 100</span></div>}
export function AnalysisResultCard({result,onAgain,onClear}:{result:AnalysisResult;onAgain:()=>void;onClear:()=>void}){
 const [copied,setCopied]=useState(false);
 const copy=async()=>{const text=`ScammerShield assessment\n${riskLabel(result.riskLevel)} · ${result.riskScore}/100\n${result.summary}\nIndicators: ${result.indicators.map(x=>x.label).join(', ')}`; try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1600);}catch{/* clipboard may be unavailable */}};
 return <section className="result-card" aria-live="polite"><div className="result-head"><div><div className="eyebrow"><ShieldAlert size={15}/> Threat analysis</div><h2>{result.category}</h2><p className="muted">{result.summary}</p></div><RiskBadge risk={result.riskLevel}/></div><div className="result-metrics"><div className="score-wrap"><RiskScore result={result}/><div><span className="metric-label">Risk score</span><strong>{result.aiStatus.includes('AI analysis available')?'AI-assisted assessment':'Local fallback'}</strong></div></div><div><span className="metric-label">Confidence</span><strong className="capitalize">{result.confidence}</strong></div><div><span className="metric-label">Input type</span><strong className="mono uppercase">{result.inputType}</strong></div></div><div className="evidence-grid"><div><div className="section-title">Why it was flagged</div>{result.indicators.map((item,i)=><div className={`evidence-item ${item.severity}`} key={`${item.label}-${i}`}><span className="evidence-icon">{item.severity==='neutral'?<Check size={13}/>:<ShieldAlert size={13}/>}</span><div><strong>{item.label}</strong><p>{item.detail}</p></div><span className="weight">{item.weight>0?`+${item.weight}`:'—'}</span></div>)}</div><div className="result-side"><div className="section-title">Assessment sources</div><div className="source-row"><span className="source-dot cyan"/>Local fallback<strong>{result.aiStatus.includes('AI analysis available')?'Ready':'Used'}</strong></div><div className="source-row"><span className="source-dot amber"/>External reputation<strong>Unavailable</strong></div><div className="source-row"><span className="source-dot pink"/>AI semantic analysis<strong>{result.aiStatus}</strong></div>{result.extractedUrls.length>0&&<div className="url-list"><div className="section-title">Extracted URLs</div>{result.extractedUrls.map(url=><a href={url.startsWith('http')?url:`https://${url}`} target="_blank" rel="noreferrer" key={url}><ExternalLink size={13}/><span>{url}</span></a>)}</div>}</div></div><div className="recommendation"><Sparkles size={16}/><div><strong>Recommended next step</strong><p>{result.recommendations[0]}</p></div></div><div className="uncertainty-box"><ShieldAlert size={15}/><div><strong>Uncertainty</strong><p>{result.uncertainty}</p></div></div><p className="disclosure">Risk score is an AI-assisted assessment based on the submitted content; local deterministic checks are used only as a fallback when AI is unavailable. <b>SAFE does not mean guaranteed safe.</b> {result.aiStatus} · {result.reputationStatus}</p><div className="result-actions"><button className="btn btn-primary" onClick={onAgain}>Scan again</button><button className="btn btn-ghost" onClick={copy}><Copy size={15}/>{copied?'Copied':'Copy result'}</button><button className="btn btn-ghost" onClick={onClear}>Clear</button></div></section>
}
